name: Sync

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: data

      - name: Run Task
        env:
          PUBLIC_KEY: ${{ secrets.RSA_PUBLIC_KEY }}
          SECRET_SCRIPT: ${{ secrets.SCRAPER_SCRIPT }}
        shell: pwsh
        run: |
          $env:SECRET_SCRIPT | Out-File -FilePath task.ps1 -Encoding utf8
          .\task.ps1
          rm task.ps1

      - name: Push Metadata
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          if ! git diff-index --quiet HEAD; then
            git commit -m "sync: $(date -u)"
            git push origin data
          fi

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -d "./temp_assets" ] && [ "$(ls -A ./temp_assets)" ]; then
            echo "Packing assets into a single archive"

            cd temp_assets
            zip -r ../vault-bundle-${{ env.RELEASE_TAG }}.zip ./*
            cd ..
            
            echo "Creating release and uploading single bundle..."
            
            gh release create ${{ env.RELEASE_TAG }} ./vault-bundle-${{ env.RELEASE_TAG }}.zip \
              --target data \
              --title "Vault ${{ env.RELEASE_TAG }}" \
              --notes "Bundled archive."
              
            echo "Release successfully created."
          else
            echo "No new assets to upload."
          fi
